# MongoDB connection
spring.data.mongodb.uri=mongodb://localhost:27017/mongo_prueba

# Puerto de tu aplicación Spring Boot (opcional, por defecto es 8080)
server.port=8080

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
